### ISSUE TITLE
tarea 2 de la practica 1

### ISSUE THREAD

**Issue by ClaraPalacios** [ClaraPalacios/prueba#2]
vamos a ver qué ocurre cuando se crea un segundo issues. con el botón de la estrella en la esquina derecha se puede hacer  una referencia a otro issue. se puede añadir al compañero con el símbolo @ 
 Esta tarea está relacionada con: #1  
@mlb0029

**Comment by mlb0029** [comment]
Gracias por la etiqueta @ClaraPalacios
